create table public.topic_threads (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  content text not null,
  category_id bigint not null,
  created_by uuid not null,
  member_count integer not null default 0,
  member_max integer not null,
  is_full boolean not null default false,
  constraint topic_threads_pkey primary key (id),
  constraint topic_threads_category_id_fkey foreign KEY (category_id) references categories (id) on update RESTRICT on delete RESTRICT,
  constraint topic_threads_created_by_fkey foreign KEY (created_by) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;