create table public.topic_threads (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text not null,
  content text not null,
  category_id bigint not null,
  created_by uuid not null,
  member_count integer not null default 0,
  member_max integer not null,
  is_full boolean not null default false,
  constraint topic_threads_pkey primary key (id),
  constraint topic_threads_category_id_fkey foreign KEY (category_id) references categories (id) on update RESTRICT on delete RESTRICT,
  constraint topic_threads_created_by_fkey foreign KEY (created_by) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;


create table public.conversations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  constraint conversations_pkey primary key (id)
) TABLESPACE pg_default;

create table public.conversation_members (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  conversation_id bigint not null,
  constraint conversation_members_pkey primary key (id),
  constraint conversation_members_conversation_id_fkey foreign KEY (conversation_id) references conversations (id) on update CASCADE on delete CASCADE,
  constraint conversation_members_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.messages (
  id bigint generated by default as identity not null,
  sent_at timestamp with time zone not null default now(),
  content text not null,
  recipient_id uuid not null,
  sender_id uuid not null,
  conversation_id bigint not null,
  constraint messages_pkey primary key (id),
  constraint messages_conversation_id_fkey foreign KEY (conversation_id) references conversations (id) on update CASCADE on delete CASCADE,
  constraint messages_recipient_id_fkey foreign KEY (recipient_id) references auth.users (id) on delete CASCADE,
  constraint messages_sender_id_fkey foreign KEY (sender_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.thread_replies (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  thread_id bigint not null,
  user_id uuid null,
  parent_comment_id bigint null,
  content text null,
  is_deleted boolean not null default false,
  constraint post_replies_pkey primary key (id),
  constraint thread_replies_parent_comment_id_fkey foreign KEY (parent_comment_id) references thread_replies (id),
  constraint thread_replies_thread_id_fkey foreign KEY (thread_id) references topic_threads (id) on update CASCADE on delete CASCADE,
  constraint thread_replies_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete set null
) TABLESPACE pg_default;

create table public.user_to_topics (
  id bigint generated by default as identity not null,
  topic_id bigint not null,
  user_id uuid not null,
  joined_at timestamp with time zone not null default now(),
  constraint group_members_pkey primary key (id),
  constraint unique_indx_topc_user unique (user_id, topic_id),
  constraint user_to_topics_topic_id_fkey foreign KEY (topic_id) references topic_threads (id) on update CASCADE on delete CASCADE,
  constraint user_to_topics_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;